### ISSUE TITLE
overview page: get rid of colour

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#323]
**URL:** https://digitalstrategie-dev.liqd.net/admin/pages/23/edit/
**user:** admin
**expected behaviour:** On the wagtail page for overview pages (common tab), I only find things that also have an effect.
**behaviour:** In the common tab, I can choose the background colour.

**Comment/Question:**  I guess the possibility to choose the background colour can also be deleted as it does not have any effect, if I get that right...?

Screenshot?
<img width="1077" alt="Bildschirmfoto 2022-03-23 um 18 12 48" src="https://user-images.githubusercontent.com/30862422/159757609-a171492d-7df8-4f73-859d-2f0bcf108240.png">

**Comment by phillimorland** [comment]
@hmkay no we just haven't done the issue yet https://github.com/liqd/digitalstrategie/issues/266

**Comment by maxliqd** [comment]
Hello, I am a little confused here: this issue hasn't been resolved yet, I think. The colours of the overview pages can still be chosen: Take a look here: https://digitalstrategie-dev.liqd.net/ergebinsse/

Introduction parts of overview pages are supposed to have a white background now. I think this issue (https://github.com/liqd/digitalstrategie/issues/266) is not relevant anymore. Sorry for all this back and forth...

**Comment by phillimorland** [comment]
the original issue https://github.com/liqd/digitalstrategie/issues/266 was to make the background colour work, we fixed that, this issue was a question asking if we should delete it if it doesn't do anything. 
Question:
'I guess the possibility to choose the background colour can also be deleted as it does not have any effect, if I get that right...?'
Answer:
'no we just haven't done the issue yet https://github.com/liqd/digitalstrategie/issues/266'
