### ISSUE TITLE
#5647 Adapt block "text with image" to styling of "text-bild-modul 50%"

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/digitalstrategie#386]
**URL:** https://digitalstrategie-dev.liqd.net/
**important screensize:** *Both*
**device & browser:** *Safari Version 15.3 (17612.4.9.1.8)*
**Comment/Question:** *01 - If possible, the spacing between Title Paragraph and Image could be a little bit more uniform, I’d try to make them the same and adjust the spacing between image and title + paragraph on Mobile.
![Screenshot-2022-04-05-at-14 35 33](https://user-images.githubusercontent.com/59610786/161791592-736175f6-9104-453f-a6db-c1d99b97bb7b.jpg)

02 – Is it possible to leave the text on the right column only?
![Screenshot 2022-04-05 at 15 24 58](https://user-images.githubusercontent.com/59610786/161791624-df524baf-8b2d-4590-938c-3c194f98a387.png)

Thanks!*

**Comment by fuzzylogic2000** [comment]
@maxliqd @hmkay I think, this is one of the issues were we have to find out if we want and need to change their styles. Or the other solution /because the differences between these two blocks were in a lot of issues) would be to restrict the pages to only allow one of these blocks (like one of them on the landing page and the other one on all the other pages or any other combination)

**Comment by maxliqd** [comment]
We will have to ask them if we can also change the spacing. It could take a little until we get an answer though.

**Comment by fuzzylogic2000** [comment]
Then the first decision to take would be: do we want that?

**Comment by maxliqd** [comment]
I think part of the spacing will look better after having changed teaser titles from h3 to h2. We can then take a look again.
