### ISSUE TITLE
alignment blocks teaser image and text with image, especially images

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#394]
**URL:** https://digitalstrategie-stage.liqd.net/
**user:** visitor
**expected behaviour:** Blocks have the same proportions and are positioned on the grid in the same way. Blocks stay aligned (size of picture, position on grid) when you zoom in.
**behaviour:** Image of teaser image is slightly more ont the right. Teaser image has larger image when you zoom in. On mobile Image of block teaser image has padding, image of text with image doesnt.
**important screensize:**Desktop, mobile
**device & browser:** Mac firefox, chrome, iphone safari
**Comment/Question:** 

Screenshot?
When you enlarge in:
![grafik](https://user-images.githubusercontent.com/94360651/162404087-54ceef9c-07ee-4b3c-b20a-6f16b36234c8.png)

Without:
![grafik](https://user-images.githubusercontent.com/94360651/162404490-42321644-1bf0-4d1f-a296-555f2d6fdd7c.png)

Mobile, teaser image:
![Digitalstrategie Berlin 2](https://user-images.githubusercontent.com/94360651/162405997-4c8399e7-f4e5-4a6d-ae3a-7e7729144265.png)

Mobile, text with image:
![Digitalstrategie Berlin](https://user-images.githubusercontent.com/94360651/162406008-fa9a3b0c-38a6-42d2-90e2-04b652369bbb.png)

**Comment by phillimorland** [comment]
@maxliqd is this the same behaviour that the sample blocks from the style guide exhibit? 
also I don't know how to fix zoom issues, until now we have only considered screen sizes, not zooming in browsers. I think if we want to ensure styling is maintained no matter the user behaviour or how browser zooms I think we need to research and it would be a technical learning or something, not sure!? either way I would say it's an edge case and probably the fix is bigger then an issue, without research though i'm not sure?!

**Comment by maxliqd** [comment]
@phillimorland Our teaser image's behaviout differs from the examples of the styleguide. On the example page no blocks exceed the main column of the grid when you zoom in. Does this help?

**Comment by phillimorland** [comment]
hopefully, cheers! :)

**Comment by fuzzylogic2000** [comment]
@phillimorland I think this issue is also about the differences of the same blocks. https://github.com/liqd/digitalstrategie/issues/396
Maybe you could have a look at both, then?

**Comment by phillimorland** [comment]
decided this is an edge case
