### ISSUE TITLE
Upper footer (light grey) first column collapsed when loading

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#403]
**URL:** https://digitalstrategie-stage.liqd.net/
**user:** visitor
**expected behaviour:** When loading, first column should not be collapsed.
**behaviour:** ??
**important screensize:**??
**device & browser:** ??
**Comment/Question:** 
@hmkay: We need to ask LR about this one, I don't understand it and cannot replicate it.
Screenshot?

**Comment by hmkay** [comment]
I don´t even know how to test the "Ladezustand", maybe @sabinammm, @phillimorland or @khamui have an idea?

**Comment by khamui** [comment]
hum, I tried, but its immediately there. I can't replicate it either @maxliqd & @hmkay .

**Comment by phillimorland** [comment]
This is from the fix for the all items being open fix have added comment, didn't know the first one should always be open, I just thought we had incorrectly copied the code, so we are sure the first item should always be open?
https://github.com/liqd/digitalstrategie/pull/274/files# 
NOTE: as we loop through the footer options rather then duplicating all the code we have to add this class just on the first loop

**Comment by hmkay** [comment]
Ah, yes, this is a Must. They wrote:

MUST: Im hellgrauen Footer-Bereich darf die erste Spalte mit den Pflichtangaben im Ladezustand nicht collapsed sein. Link zum korrekten Markup im Styleguide: http://styleguide.berlin.de/patterns/09-vertical_marketing-page-global-footer/09-vertical_marketing-page-global-footer.html
🤷

**Comment by phillimorland** [comment]
That's very odd ux consistency wise but ok
