### ISSUE TITLE
elasticsearch highlights might be empty

### ISSUE THREAD

**Issue by goapunk** [liqd/digitalstrategie#420]
we had sentry errors where it wouldn't find the 'fields' key during the fetching of the search highlights. Add a check if if exists before accessing it

**Comment by fuzzylogic2000** [comment]
We only wanted to do that when it occurs again, right?

**Comment by goapunk** [comment]
Yeah let's wait for it to happen again and only do it if really necessary

**Comment by phillimorland** [comment]
@goapunk is this still relevant or can it be closed?

**Comment by goapunk** [comment]
we didn't fix anything afair so it could still be an issue, just nobody is really using the search I guess

**Comment by fuzzylogic2000** [comment]
@goapunk We cannot really do anything about it, right?

@maxliqd That would mean that we cannot fix it and have to wait for the wagtail update that fixes it. Also, I think so far, this wasn't reported or encountered by any user? So it might currently be not that important and we can look at it when we need to because it happens more often.

**Comment by maxliqd** [comment]
@fuzzylogic2000 Ok thank you, I will close the issue for now.
