### ISSUE TITLE
Info on accessibility in header navigation empty in leichte Sprache when 500 error

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#924]
**Essential Information**
**URL:**https://gd-stage.liqd.net/de-ls/search/?q=gelogen
**device & browser:**
**operating system (incl. version):**
**behaviour:**
**expected behaviour:**

**Additional information if relevant**
**user role:**
**important screensize:**
**Comment/Question:**

**Screenshot if design related**:
Since issues are public, make sure to not display personal or secret data.
![image](https://github.com/liqd/digitalstrategie/assets/94360651/4df3fa47-519d-46c9-b8ac-7dd96e831617)

**Comment by philli-m** [comment]
@maxliqd I talked to @goapunk about this and it is somewhat expected behavior as a 500 is a server error and the accessibility information comes from the server, it might be possible to add a back hard-coded version or something but it would be a lot of work. What is the priority for this?
Also as the error page requests you return to homepage, does the information show after you have changed pages? if so I would suggest this is not a big problem but let us know what you think!

**Comment by goapunk** [comment]
@maxliqd by returning to the homepage you mean clicking the logo? This always resets the language currently. (e.g. on an english browser it will always return to english, even after switching to the german site)
