### ISSUE TITLE
page cannot be edited via wagtail

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/digitalstrategie#978]
**Essential Information**
**URL:** https://gd-stage.liqd.net/de/strategie
**device & browser:** any
**operating system (incl. version):**any 
**behaviour:** 500 error 
**expected behaviour:** I can edit the strategy page via wagtail

**Additional information if relevant** see comments below
**user role:** admin
**important screensize:**
**Comment/Question:** only on stage, not on prod

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow can you reproduce this issue and do you have any idea why it is not on prod but only on stage? anything related to wagtail settings or really a bug?

**Comment by sblindow** [comment]
@CarolingerSeilchenspringer this issue is reproduceable for me on stage as well. The fact that It works fine on prod however, and that the page type and the different Blocks work fine on other pages might point to an isolated issue. One more thing that I noticed was that the Strategie page has a simple language version, that the prod equivalent doesn't have.

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow thanks for confirming. We should look into it and make sure it isn't something that would go on prod with the next release.
